FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install pandas
RUN pip install transformers
RUN pip install sentencepiece
RUN pip install fastapi
RUN pip install requests
RUN pip install torch==1.11.*
